name: 'lint_web.yaml'
on:
  - 'workflow_call'
  - 'workflow_dispatch'

permissions: { }

jobs:
  prettier:
    runs-on: 'ubuntu-26.04'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v7.0.1'
      - name: 'Run prettier in webclient'
        working-directory: 'clients/web'
        run: |
          npm ci
          npm run prettier
  eslint:
    runs-on: 'ubuntu-26.04'
    permissions:
      checks: 'write'
      contents: 'read'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v7.0.1'
      - name: 'Run eslint with reviewdog'
        uses: 'reviewdog/action-eslint@v1.34.0'
        # https://github.com/marketplace/actions/run-eslint-with-reviewdog
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          level: 'warning'
          reporter: 'github-check'
          fail_level: 'warning'
          workdir: 'clients/web'
